name: slicem

dependencies:
  - python=3.6.8
  - scipy==1.3.0
  - pandas==0.24.2
  - matplotlib==3.1.1
  - numpy==1.14.2
  - scikit-image==0.15.0
  - pip:
    - mrcfile==1.1.2
    - networkx==2.1
    - python-igraph